# Project info
site_name: remote-watering
site_url: https://z.rootnode.duckdns.org/46265z/remote-watering # https://46265z.github.io/IoT-dev-setup/
site_author: Alexander A. Parvanov
site_description: >-
  arduino template repository

# Repository
repo_name: 46265z/remote-watering
repo_url: https://z.rootnode.duckdns.org/46265z/remote-watering
# edit_url: ""

theme:
  name: material
    
    # 404 page
  static_templates:
    - 404.html

    # Necessary for search to work properly
  include_search_page: false
  search_index_only: true
    
    # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.indexes
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
  # - pdf-export
  # - redirects:
  #     redirect_maps:
  #       extensions/admonition.md: reference/admonitions.md
        # extensions/codehilite.md: reference/code-blocks.md
  #       extensions/footnotes.md: reference/footnotes.md
  #       extensions/metadata.md: reference/meta-tags.md
  #       extensions/permalinks.md: setup/setting-up-navigation.md #permalink
  #       extensions/pymdown.md: reference/admonitions.md
  #       plugins/revision-date.md: setup/adding-a-git-repository.md #revision-date
  #       plugins/search.md: setup/setting-up-site-search.md
  #       releases/4.md: upgrading.md #upgrading-from-4x-to-5x
  #       releases/5.md: upgrading.md #upgrading-from-3x-to-4x
  #       releases/changelog.md: changelog.md
  #       setup/adding-social-links.md: setup/setting-up-the-footer.md
  #       sponsorship.md: insiders.md
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.snippets:
      base_path: docs
  - toc:
      permalink: true
      # slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: 46265z
      repo: remote-watering
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - Project layout: index.md
  - Examples:
    - Getting started: examples/getting-started.md
    - Auto Watering: examples/auto-watering.md
  - Sketches:
    - Manual Watering: sketches/manual-watering.md
